[build]
target = "avr-atmega328p.json"

[unstable]
build-std = ["core"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 9600"

[env]
AVR_CPU_FREQUENCY_HZ = "16000000"
